"""create posts table

Revision ID: ae6f8ae7c234
Revises: 13d8ab09fc40
Create Date: 2025-02-12 05:06:33.209712

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae6f8ae7c234"
down_revision: Union[str, None] = "13d8ab09fc40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_phrase", sa.String(length=50), nullable=False, comment="五音"),
        sa.Column("second_phrase", sa.String(length=50), nullable=False, comment="七音"),
        sa.Column("third_phrase", sa.String(length=50), nullable=False, comment="五音"),
        sa.Column("full_text", sa.String(length=255), nullable=False, comment="完全な俳句"),
        sa.Column("note", sa.Text(), nullable=True, comment="補足説明、メモ等"),
        sa.Column("season", sa.String(length=20), nullable=True, comment="季節"),
        sa.Column("kigo", sa.String(length=50), nullable=True, comment="季語"),
        sa.Column(
            "posted_at", sa.DateTime(timezone=True), nullable=False, comment="俳句の投稿日時"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="レコード作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="レコード更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_id"), "posts", ["id"], unique=False)
    op.create_index(op.f("ix_posts_kigo"), "posts", ["kigo"], unique=False)
    op.create_index(op.f("ix_posts_season"), "posts", ["season"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_season"), table_name="posts")
    op.drop_index(op.f("ix_posts_kigo"), table_name="posts")
    op.drop_index(op.f("ix_posts_id"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
